# Arrow Flight SQL JDBC driver (recommended)
# jdbc.url = jdbc:arrow-flight-sql://localhost:32010
jdbc.url = jdbc:arrow-flight-sql://dremio:32010?useEncryption=false
jdbc.user = dremio
jdbc.password = dremio123
jdbc.driver = org.apache.arrow.driver.jdbc.ArrowFlightJdbcDriver

logging.level.it.unibz.inf.ontop=TRACE
logback.log.level=TRACE

ontop.queryLogging=true
ontop.queryLogging.includeReformulatedQuery=true
ontop.queryLogging.includeSparqlQuery=true
ontop.queryLogging.includeClassesAndProperties=false
ontop.queryLogging.includeTables=false


# # Performance settings
# org.obda.owlreformulationplatform.aboxmode = virtual
# org.obda.owlreformulationplatform.rewriting = true
# org.obda.owlreformulationplatform.distinctResultSet = false

# # Logging
# logging.level.org.obdap = INFO

# # PostgreSQL JDBC driver
# jdbc.url=jdbc:postgresql://postgres_db:5432/tourism
# jdbc.driver=org.postgresql.Driver
# jdbc.user=postgres_user
# jdbc.password=postgres_password

# # Trino JDBC driver
# url = jdbc:trino://localhost:8090/defaultdatabase
# jdbc.user = user
# jdbc.password = password
# jdbc.driver = io.trino.jdbc.TrinoDriver